project:
  type: website
  output-dir: docs

website:
  title: "Jesse Onland"
  site-url: "https://jdonland.github.io/"
  favicon: image.jpg
  search: false
  page-footer: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Projects
      - href: links.qmd 
        text: Links
      - href: resume.pdf
        text: Resume

format:
  html:
    reference-location: margin
    citation-location: margin
    theme: 
      - simplex
      - theme.scss
    mainfont: Palatino
    linkcolor: "#dc2828"
    grid:
      sidebar-width: 300px
      body-width: 723px
      margin-width: 300px
    code-copy: false
    code-fold: true
    lightbox: true
    anchor-sections: false
    link-external-newwindow: true
    date-format: long
    execute: 
      warning: false
      message: false

editor: source